---
version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tickets_sell
