server:
  port: 8080

logging:
  file.name: payment-debug.log
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG
    com.denysenko: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
#    io:
#      r2dbc:
#        postgresql: TRACE

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/ticket_sell?schema=public?connectionTimeZone=UTC
    username: admin
    password: admin
    pool:
      enabled: false
  mvc:
    log-request-details: true

