server:
  port: 8080


logging:
  file:
    name:
      /logs/app.log
  level:
    root: ERROR
    org.springframework.web: TRACE
    org.springframework.r2dbc: TRACE
    com.denysenko: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
#    io:
#      r2dbc:
#        postgresql: TRACE

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/ticket_sell?schema=ticket_sell?connectionTimeZone=UTC
    username: admin
    password: admin
    pool:
      enabled: false
  mvc:
    log-request-details: true

#  data:
#    r2dbc:
#      repositories:
#        enabled: true

#  datasource:
#    hikari:
#      connection-init-sql: SET TIME ZONE 'UTC'

