server:
  port: 8081

logging:
  file:
    name:
      /logs/app.log
  level:
    root: ERROR
    org.springframework.web: TRACE
    org.springframework.r2dbc: DEBUG
    com.denysenko: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:15432/ticket_sell?schema=ticket_sell
    username: admin
    password: admin
    pool:
      enabled: false
  mvc:
    log-request-details: true
