server:
  port: 8081

logging:
  file.name: ticketcontrol-debug.log
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG
    com.denysenko: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
#    io:
#      r2dbc:
#        postgresql: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:15432/ticket_sell?currentSchema=public,connectionTimeZone=UTC
    username: admin
    password: admin
    pool:
      enabled: false
  mvc:
    log-request-details: true
